name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.10.0

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      working-directory: my-app

    - name: Install Eslint plugin
      run: npm install eslint-plugin-react@latest --save-dev --legacy-peer-deps
      working-directory: my-app

    - name: Run Eslint
      run: npm run lint
      working-directory: my-app

    # - name: Run tests
    #   run: npm test
    #   working-directory: my-app
